# Generated by Django 3.1.4 on 2020-12-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
