# Generated by Django 3.1.4 on 2021-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_text', models.CharField(max_length=150, verbose_name='Action Text')),
                ('action_url', models.URLField(verbose_name='Action Url')),
                ('image', models.ImageField(upload_to='slideShowPictures/', verbose_name='Image')),
            ],
        ),
    ]
