# Generated by Django 3.1.4 on 2021-01-09 09:58

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('end_time', models.DateTimeField(verbose_name='End At')),
                ('show', models.BooleanField(verbose_name='Show Status')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('image', models.ImageField(upload_to='', verbose_name='Offer Background')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Offer Card',
                'verbose_name_plural': 'Offer Cards',
            },
        ),
        migrations.CreateModel(
            name='SlideShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_text', models.CharField(max_length=150, verbose_name='Action Text')),
                ('action_url', models.URLField(verbose_name='Action Url')),
                ('image', models.ImageField(upload_to='slideShowPictures/', verbose_name='Background')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Slide Images',
                'verbose_name_plural': 'Slide Images',
            },
        ),
    ]
