# Generated by Django 3.1.4 on 2021-01-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercards',
            name='action_text',
            field=models.CharField(max_length=70, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='action_text',
            field=models.CharField(max_length=70, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
