# Generated by Django 3.1.4 on 2021-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferCards',
        ),
        migrations.AddField(
            model_name='slideshowimage',
            name='crop_it',
            field=models.BooleanField(default=False, verbose_name='Crop It'),
        ),
    ]
