# Generated by Django 3.1.4 on 2021-01-26 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteview', '0002_auto_20210126_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowimage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 10, 8, 44, 320823, tzinfo=utc), verbose_name='End At'),
            preserve_default=False,
        ),
    ]
