# Generated by Django 3.1.4 on 2021-01-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteview', '0002_auto_20210110_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercards',
            name='action_text',
            field=models.CharField(max_length=35, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='offercards',
            name='description',
            field=models.CharField(max_length=120, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='action_text',
            field=models.CharField(max_length=35, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='description',
            field=models.CharField(max_length=120, verbose_name='Description'),
        ),
    ]
