# Generated by Django 3.1.4 on 2021-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteview', '0003_auto_20210115_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercards',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
    ]
