# Generated by Django 3.1.4 on 2020-12-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='basket',
        ),
    ]
