# Generated by Django 3.1.4 on 2021-02-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
