# Generated by Django 3.1.4 on 2021-01-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='basket',
            new_name='cart',
        ),
    ]
