# Generated by Django 3.1.4 on 2021-01-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_auto_20210123_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='send_time',
        ),
    ]
