# Generated by Django 3.1.4 on 2021-02-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_auto_20210206_1203'),
        ('app_order', '0002_cartmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_meta', related_query_name='order_meta', to='app_order.order', verbose_name='cart')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_meta', related_query_name='order_meta', to='app_product.shopproduct', verbose_name='shop_product')),
            ],
        ),
    ]
