# Generated by Django 3.1.4 on 2021-02-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeta',
            name='value',
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('product_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', related_query_name='value', to='app_product.productmeta', verbose_name='Value')),
            ],
        ),
    ]
