# Generated by Django 3.1.4 on 2021-01-10 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 10, 7, 59, 19, 539192, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AddField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 10, 7, 59, 35, 889352, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 10, 7, 59, 52, 730181, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AddField(
            model_name='shop',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 10, 7, 59, 59, 681982, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
