# Generated by Django 3.1.4 on 2020-12-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_like'),
        ('app_product', '0002_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_shop', related_query_name='product_shop', to='app_account.shop', verbose_name='Shop'),
            preserve_default=False,
        ),
    ]
