# Generated by Django 3.1.4 on 2021-01-23 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_auto_20210110_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 23, 16, 29, 9, 250601, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
