# Generated by Django 3.1.4 on 2021-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_remove_brand_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmeta',
            options={'verbose_name': 'Product Meta Detail', 'verbose_name_plural': "Product Meta Detail's"},
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip Address')),
                ('hits', models.ManyToManyField(blank=True, related_name='hits', to='app_product.Category', verbose_name='Views')),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addressees',
            },
        ),
    ]
