# Generated by Django 3.1.4 on 2021-02-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_auto_20210202_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmeta',
            options={'verbose_name': 'Product Meta Detail'},
        ),
    ]
